version: "3"
services:
  app:
    container_name: app
    build: ./app
    volumes:
      - ./app:/app
    links:
      - mysql
    ports:
      - "8000:8000"
    networks:
      - clientnet
    restart: on-failure


  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql/stock.sql:/docker-entrypoint-initdb.d/stock.sql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - clientnet
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

    
networks:
  clientnet:
    name: client_network