version: "3"
services:
  app:
    container_name: app
    build: ./
    volumes:
      - .:/app
    links:
      - mysql
    ports:
      - "8000:8000"
      
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: STOCK_STREAMING
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
