variable "name" {}
variable "region" {}
variable "vpc_id" {}
variable "access_key" {}
variable "secret_key" {}
variable "public_subnet_id" {}
variable "private_subnet_id" {}
variable "s3_stock_bucket_endpoint" {}
variable "s3_stock_bucket" {}
variable "s3_stock_folder" {}
