GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'replicator' IDENTIFIED BY 'replpass';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT  ON *.* TO 'root' IDENTIFIED BY 'root';

CREATE DATABASE IF NOT EXISTS STOCK_STREAMING;
GRANT ALL PRIVILEGES ON STOCK_STREAMING.* TO 'mysqluser'@'%';

USE STOCK_STREAMING;

CREATE TABLE IF NOT EXISTS IBM_STOCK (
    time DATETIME NOT NULL,
    open FLOAT NOT NULL,
    high FLOAT NOT NULL,
    low FLOAT NOT NULL,
    close FLOAT NOT NULL,
    volume FLOAT NOT NULL,
    symbol VARCHAR(40),
    event_time DATETIME DEFAULT NOW(),
    PRIMARY KEY (time)
);

SELECT * FROM IBM_STOCK;