services:
  zookeeper:
    image: quay.io/debezium/zookeeper:3.0
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    # networks:
    #   - client_default

  kafka:
    image: quay.io/debezium/kafka:3.0
    links:
     - zookeeper
    depends_on:
      - zookeeper
    ports:
     - 9092:9092
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
    #  - ADVERTISED_HOST_NAME=0.0.0.0
    # networks:
    #   - client_default


  connect:
    image: quay.io/debezium/connect:3.0
    links:
     - kafka
    ports:
     - 8083:8083
    depends_on:
      - kafka
      - zookeeper
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - HOST_NAME=0.0.0.0
    # networks:
    #   - client_default

# networks:
#   client_default:
#     external: true