version: "3"
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:3.0
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    network_mode: host
    # networks:
    #   - client_default

  kafka:
    image: quay.io/debezium/kafka:3.0
    links:
     - zookeeper
    depends_on:
      - zookeeper
    ports:
     - 9092:9092
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
    network_mode: host
    #  - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=BROKER:PLAINTEXT,SSL:SSL,CONTROLLER:PLAINTEXT
    #  - KAFKA_LISTENERS=BROKER://0.0.0.0:9093,SSL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9094
    #  - KAFKA_ADVERTISED_LISTENERS=SSL://localhost:9092,BROKER://localhost:9093
    #  - ADVERTISED_HOST_NAME=localhost
    # networks:
    #   - client_default


  connect:
    image: quay.io/debezium/connect:3.0
    links:
     - kafka
    ports:
     - 8083:8083
    depends_on:
      - kafka
      - zookeeper
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    network_mode: host
    #  - HOST_NAME=localhost
    # networks:
    #   - client_default

# networks:
#   client_default:
#     external: true