services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql/stock.sql:/docker-entrypoint-initdb.d/stock.sql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
      
  zookeeper:
    image: quay.io/debezium/zookeeper:3.0
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    # networks:
    #   - client_default

  kafka:
    image: quay.io/debezium/kafka:3.0
    links:
     - zookeeper
    depends_on:
      - zookeeper
    ports:
     - 9092:9092
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${INSTANCE_PRIVATE_IP}:9092
     - KAFKA_ADVERTISED_HOST_NAME=${INSTANCE_PRIVATE_IP}
     - KAFKA_ADVERTISED_PORT=9092
    # networks:
    #   - client_default


  connect:
    image: quay.io/debezium/connect:3.0
    links:
     - kafka
    ports:
     - 8083:8083
    depends_on:
      - kafka
      - zookeeper
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8083/connectors"]
      interval: 10s
      timeout: 30s
      retries: 5
    # networks:
    #   - client_default

# networks:
#   client_default:
#     external: true