services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./config/stock.sql:/docker-entrypoint-initdb.d/stock.sql
      - ./config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s