variable "name" {}
variable "vpc_id" {}
variable "private_subnet_id" {}
variable "region" {}
variable "debezium_private_ip" {}
variable "debezium_sg_id" {}
variable "access_key" {}
variable "secret_key" {}
variable "s3_stock_bucket" {}
variable "s3_stock_folder" {}
